"""unique email and username for User model

Revision ID: d2e51626eb73
Revises: 322105a544e5
Create Date: 2024-05-30 18:03:01.074888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd2e51626eb73'
down_revision: Union[str, None] = '322105a544e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_unique_constraint('uq_user_username', ['username'])
    # op.create_unique_constraint(None, 'user', ['email', 'username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_constraint('uq_user_username', type_='unique')
    # ### end Alembic commands ###
